server:
  port: 8889
  servlet:
    context-path: /manager
  max-http-header-size: 102400
  session:
    timeout=7200:
spring:
  redis:
    database: 5
    host: 192.168.1.55
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 10
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Shanghai
primary:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/persie_deamon?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
second:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/persie?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: root
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
third:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://103.20.249.243:3307/minigameback?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true
      username: queryMiniWx
      password: blazefire103.
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
config:
  upload: d:/upload/normal
  domain: http://192.168.1.126:8888/upload/
  excelSave: d:/upload/excel
  matchRes: https://res.qinyougames.com/match/
  readRes: /data/res.qinyougames.com/persieRes/
  resHost: https://res.qinyougames.com/persieRes/
  flushCache: https://logic.qinyougames.com/persieService/flush/logic
  flushPublicCache: https://sgame.qinyougames.com/public/flush/logic
  flushOnline: http://129.211.119.249:10085/persieDeamon/query/online
  wxQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
  supplementUrl: http://192.168.1.55:8080/persieService/pay/callback